# -*- coding: utf-8 -*-
"""Day-9-python-and-ml-pre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izmj7mFJQ0fTkqhEySxsyMl2vPjyYco7
"""

import pandas as pd

dataset=pd.read_csv('/content/Salary_Data.csv')
dataset.count()

dataset.head()

dataset.describe()

dataset.info()

import matplotlib.pyplot as plt
plt.plot(dataset);

import seaborn as sns
sns.scatterplot(x=dataset['YearsExperience'],y=dataset['Salary']);

# split the dataset into training and testing 
# define x and y

x=dataset.iloc[:,:-1].values # all rows escept last column
y=dataset.iloc[:,-1].values # all rows with only last column

print(x)

print(y)

# split dataset into training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,train_size=0.7,test_size=0.3,random_state=0)