# -*- coding: utf-8 -*-
"""day-3-homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1st9SbzUjVt3u5TQ45y-oCdexUWJgZO7I
"""

# create list of five characters and print each character five times
ch_list = ['a', 'b', 'c','d', 'e']

for i in ch_list:
  print(i*5)

# take list of random 10 values and create list of even and odd numbers

random_list = [23, 45, 56, 79, 8, 38, 54, 6, 67, 23]
even_list = []
odd_list = []

for i in random_list:
  if(i % 2 == 0):
    even_list.append(i)
  else:
    odd_list.append(i)

print("Even list:")
print(even_list)
print("Odd list")
print(odd_list)

# create dictionary for student with its details and print keys and values separately
student_data = {
        "name": "Tony",
        "roll_no": '1',
        "class": "SE",
        "div": "11",
        "city": "Nashik"
}

print(student_data)
print(student_data.keys())
print(student_data.values())

# create list and caclculate square of each number
test = [
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]
]

# print(test)

for i in test:
  for j in i:
    print(j, j*j)