# -*- coding: utf-8 -*-
"""Day 1 python course.ipynb
G Sudarshan
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI34oR5wX7YwLJizVRd4s34k7rVxPI3M
"""

# Hello world program
print("hello world")

# program to print average of 5 numbers
a = int(input("Enter Number : "))
b = int(input("Enter Number : "))
c = int(input("Enter Number : "))
d = int(input("Enter Number : "))
e = int(input("Enter Number : "))
average = (a+b+c+d+e)/5
print("Average : {}".format(average))

# program to print greater nummber 
a = int(input("Enter a : "))
b = int(input("Enter b : "))
if a > b:
  print("a is greater")
else:
  print("b is greater")

a = int(input("Enter a : "))
b = int(input("Enter b : "))
if a > b:
  print("a is greater")
elif b > a:
  print("b is greater")
else: 
  print("a and b are equal")

print("The main code")

# program to print greater nummber among 3 numbers
a = int(input("Enter a : "))
b = int(input("Enter b : "))
c = int(input("Enter c : "))

if (a > b) and (a > c):
  print("a is largest")  
elif (b >= a) and (b >= c):
  print("b is largest")  
else:
  print("c is largest")

# program t find largest and smallest element from 6 elements
a = int(input("Enter a : "))
b = int(input("Enter b : "))
c = int(input("Enter c : "))
d = int(input("Enter d : "))
e = int(input("Enter e : "))
f = int(input("Enter f : "))

largest = max(a,b,c,d,e,f);
smallest = min(a,b,c,d,e,f)

print("largest no is ",largest)
print("smallest no is ",smallest)

# program to perform arithmatic operations
a = int(input("Enter a : "))
b = int(input("Enter b : "))

operation = int(input("which operation do you want to perform 1.add 2.subtract 3.multiply 4.divide :"))
if(operation==1):
  print(a+b)
elif(operation==2):
  print(a-b)
elif(operation==3):
  print(a*b)
elif(operation==4):
  print(a/b)

print("done")

# for loop
for a in range(1,10,4):
  print(a)

# table
num = int(input("Enter a number: "))
print("----------")

for a in range(num,num*10+1,num):
  print(a)

# factorial
num = int(input("Enter a number: "))
fact = 1

for i in range(1, num+1):
  fact = fact * i

print("Factorial is:",fact)

# while loop
a = 0 
while a < 10:
  print(a)
  a = a + 1