# -*- coding: utf-8 -*-
"""day-1-homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VGmLM_CHFZQabwAlMGWl9ksSrnRJpgiD
"""

# Write a python program to print square of all numbers from 1 to 10
for i in range(1,11):
  print(i*i)

# Find the sum of all even numbers between 0 to 10
sum = 0 

for i in range(0,11,2):
  sum += i

print("sum of all even numbers between 0 to 10:",sum)

# Write a python program to read the numbers (x,y,z) and check how many of them are between 10 and 100

x = int(input("Enter x: "))
y = int(input("Enter y: "))
z = int(input("Enter z: "))

res = 0

if(10<=x<=100):
  res = res + 1
if(10<=y<=100):
  res = res + 1
if(10<=z<=100):
  res = res + 1

print("{0} numbers are in between 10 and 100".format(res))

# Accept a number and find reverse of it.
num = int(input("Enter the number: "))
res = 0

while(num != 0):
  res = res * 10 + num%10
  num = num // 10

print("reverse number is {0} ".format(res))