# -*- coding: utf-8 -*-
"""Day-8-python-ml-pre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoayT8deFBvmHayM3Hu6V9RaBIdi7WAu
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

tips_df = sns.load_dataset("tips");

tips_df

sns.barplot(x='day', y='total_bill', data=tips_df);

sns.barplot(x='day', y='total_bill', hue='sex', data=tips_df);

sns.barplot(x='total_bill', y='day', hue='sex', data=tips_df);

# heatmap
flights_df = sns.load_dataset("flights").pivot("month", "year", "passengers")

flights_df

plt.title("No. of Passengers (1000s)")
sns.heatmap(flights_df);

plt.title("No. of Passengers (1000s)")
sns.heatmap(flights_df, fmt="d", annot=True, cmap='Blues');

# images
from urllib.request import urlretrieve
import numpy as np

urlretrieve('https://i.imgur.com/SkPbq.jpg', 'chart.jpg');
from PIL import Image

img = Image.open('chart.jpg')

img_array = np.array(img)
img_array.shape

plt.imshow(img);

plt.grid(False)
plt.title('A data science meme')
plt.axis('off')
plt.imshow(img);

plt.grid(False)
plt.axis('off')
plt.imshow(img_array[125:325,105:305]);

# Plotting multiple charts in a grid
fig, axes = plt.subplots(2, 3, figsize=(16, 8))

axes[1,2].set_title('Data Science Meme')
axes[1,2].imshow(img)
axes[1,2].grid(False)
axes[1,2].set_xticks([])
axes[1,2].set_yticks([])
plt.tight_layout(pad=2);

axes[1,0].set_title('Restaurant bills')
sns.barplot(x='day', y='total_bill', hue='sex', data=tips_df, ax=axes[1,0]);

axes[1,1].set_title('Flight traffic')
sns.heatmap(flights_df, cmap='Blues', ax=axes[1,1]);

sns.pairplot(tips_df, hue='sex');

flowers_df = sns.load_dataset("iris")

sns.pairplot(flowers_df, hue='species');